/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Messenger.PrijataSprava;
import Messenger.SMS;
import dp.OdpadoveHospodarstvo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rendo
 */
public class JF_Messenger extends javax.swing.JFrame {

    //LinkedList<PrijataSprava> nespracovaneSpravy;
    boolean odpovedam = false;
    OdpadoveHospodarstvo oh;

    /**
     * Creates new form JF_Messenger
     */
    public JF_Messenger(OdpadoveHospodarstvo oh) {
        //initComponents();
        if (oh.getNespracovaneSpravy().size() <= 0) {
            JOptionPane.showMessageDialog(this, "Nie sú žiadne nespracované správy");
            return;
        } else {
            initComponents();
            this.oh = oh;
            jLabel1.setText("Dátum: ");
            jLabel2.setText("Odosielateľ: ");
            jLabel3.setText("-1");
            jLabel3.setVisible(false);
            jTable1.setModel(getSpravy());
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        }
    }

    public DefaultTableModel getSpravy() {
        DefaultTableModel mod = null;
        mod = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
//                    if (column == 0 || column == 1 || column == 2 || column == 3) {
//                        return Integer.class;
//                    } else if (column == (columnCount - 2)) {
//                        return Boolean.class;
//                    }
                return Object.class;
            }
            boolean[] canEdit = new boolean[]{
                false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        Object[] header = new Object[3];
        header[0] = "Dátum prijatia";
        header[1] = "Odosielateľ";
        header[2] = "Správa";
        mod.setColumnIdentifiers(header);
        SimpleDateFormat simpleDateFormat2 = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        for (PrijataSprava prijataSprava : oh.getNespracovaneSpravy()) {
            Object[] data = {simpleDateFormat2.format(prijataSprava.getDatum()), prijataSprava.getTel(), prijataSprava.getText()};
            mod.addRow(data);
        }

        return mod;
    }

    public JF_Messenger() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nespracované správy");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jTextPane1);

        jButton1.setText("Vymaž správu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Odpovedať");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(35, 35, 35))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (odpovedam == false) {
            int row = jTable1.rowAtPoint(evt.getPoint());
            SimpleDateFormat simpleDateFormat2 = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            jLabel1.setText("Dátum: " + simpleDateFormat2.format(oh.getNespracovaneSpravy().get(row).getDatum()));
            jLabel2.setText("Odosielateľ: " + oh.getNespracovaneSpravy().get(row).getTel());
            jLabel3.setText("" + row);
            jTextPane1.setText(oh.getNespracovaneSpravy().get(row).getText());
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (jButton1.getText().equals("Vymaž správu")) {
                int index = Integer.parseInt(jLabel3.getText());
                if (index < 0) {
                    JOptionPane.showMessageDialog(this, "Prosím, vyberte správu ktorú chcete vymazať");
                    return;
                }
                Object[] ponuka = {"Áno", " Nie"};
                int moznost = JOptionPane.showOptionDialog(this,
                        "Naozaj chcete vymazať správu:\n"
                        + jLabel1.getText() + "\n"
                        + jLabel2.getText() + " ?",
                        "Vymazanie nespracovanej správy",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, //ikona
                        ponuka,
                        ponuka[0]);
                if (moznost == 0) {
                    jLabel1.setText("Dátum: ");
                    jLabel2.setText("Odosielateľ: ");
                    jLabel3.setText("-1");
                    jTextPane1.setText("");
                    oh.getNespracovaneSpravy().remove(index);
                    Refresher.r.refresNespracovaneSpravy();
                    jTable1.setModel(getSpravy());
                    jTable1.clearSelection();
                }
            } else {
                jButton1.setText("Vymaž správu");
                jButton2.setText("Odpovedať");
                jTable1.setEnabled(true);
                jLabel1.setText("Dátum: ");
                jLabel2.setText("Odosielateľ: ");
                jLabel3.setText("-1");
                jTextPane1.setText("");
                jTable1.clearSelection();
                odpovedam = false;
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jButton2.getText().equals("Odpovedať")) {
            if (Integer.parseInt(jLabel3.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Prosím, vyberte správu na ktorú chcete odpovedať");
                return;
            }
            jButton2.setText("Odoslať");
            jButton1.setText("Späť");
            jTable1.setEnabled(false);
            jTextPane1.setText("Sem napíšte odpoveď ...");
            odpovedam = true;
        } else if (jButton2.getText().equals("Odoslať")) {
            if (Integer.parseInt(jLabel3.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Prosím, vyberte správu na ktorú chcete odpovedať");
                return;
            }
            String text = jTextPane1.getText();
            if (text.startsWith("Sem napíšte odpoveď")) {
                JOptionPane.showMessageDialog(this, "Prosím zadajte text správy");
                return;
            }
            int index = Integer.parseInt(jLabel3.getText());
            ArrayList<String> prijimatelia = new ArrayList<>();
            prijimatelia.add(oh.getNespracovaneSpravy().get(index).getTel());
            String txt = oh.getMsg().posliSMS(new SMS(text, "OHRajec", prijimatelia));
            if (txt.equals("problem")) {                
                JOptionPane.showMessageDialog(this, "Nepodarilo sa pripojiť k sms bráne");
                return;
            } else if (txt.startsWith("OK")) {
                JOptionPane.showMessageDialog(this, "Úspešne ste odpovedali na sms");
            } else {
                JOptionPane.showMessageDialog(this, txt);
                return;
            }
            jButton2.setText("Odpovedať");
            jButton1.setText("Vymaž správu");
            odpovedam = false;
            Object[] ponuka = {"Áno", " Nie"};
            int moznost = JOptionPane.showOptionDialog(this,
                    "Naozaj chcete vymazať správu:\n"
                    + jLabel1.getText() + "\n"
                    + jLabel2.getText() + " ?",
                    "Vymazanie nespracovanej správy",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //ikona
                    ponuka,
                    ponuka[0]);
            if (moznost == 0) {
                jLabel1.setText("Dátum: ");
                jLabel2.setText("Odosielateľ: ");
                jLabel3.setText("-1");
                jTextPane1.setText("");
                oh.getNespracovaneSpravy().remove(index);
                Refresher.r.refresNespracovaneSpravy();
                jTable1.setModel(getSpravy());
            }
            jTable1.clearSelection();
            jTable1.setEnabled(true);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Messenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
